export default {
    NEW_SERVICE: 'NEW_SERVICE',
    NEW_SERVICE_ITEM: 'NEW_SERVICE_ITEM',
    SERVICE_ITEM_LOADING: 'SERVICE_ITEM_LOADING',
    USER_REGISTERED: 'USER_REGISTERED',
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    ADD_RESERVE: 'ADD_RESERVE',
    FIND_RESERVE: 'FIND_RESERVE',
    IS_ADMIN: 'IS_ADMIN',
    AUTH_ERROR: 'AUTH_ERROR',
    FETCH_USER: 'FETCH_USER'
}