export const GET_MY_ORDERS_REQUEST = 'GET_MY_ORDERS_REQUEST'
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS'
export const GET_MY_ORDERS_FAILURE = 'GET_MY_ORDERS_FAILURE'

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE'