export const SETUP_STORE_REQUEST = 'SETUP_STORE_REQUEST'
export const SETUP_STORE_SUCCESS = 'SETUP_STORE_SUCCESS'
export const SETUP_STORE_FAILURE = 'SETUP_STORE_FAILURE'


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'